/**:
  ros__parameters:
    right:
      min_longitudinal_offset: 3.235
      max_longitudinal_offset: 3.965
      min_lateral_offset: -0.994
      max_lateral_offset: -0.679
      min_height_offset: 0.65
      max_height_offset: 1.370
    left:
      min_longitudinal_offset: 3.05
      max_longitudinal_offset: 4.730
      min_lateral_offset: 0.39
      max_lateral_offset: 1.28
      min_height_offset: 0.65
      max_height_offset: 1.435
